DEMO_RECORDS = [
    {"id": 1, "text": "Data retention policy requires yearly review and approval."},
    {"id": 2, "text": "Unauthorized login attempts were detected from unknown IPs."},
    {"id": 3, "text": "Employee onboarding policy needs HR manager approval."},
    {"id": 4, "text": "Finance expense claims must be verified before payment."},
    {"id": 5, "text": "Access control policy requires multi-factor authentication."},
    {"id": 6, "text": "Vendor contract renewal is pending legal review."},
    {"id": 7, "text": "Password policy requires minimum 12 characters."},
    {"id": 8, "text": "Audit logs must be stored for 180 days."},
    {"id": 9, "text": "Remote work policy needs updated security guidelines."},
    {"id": 10, "text": "Database backup policy requires weekly validation."},
    {"id": 11, "text": "User role permissions should be reviewed monthly."},
    {"id": 12, "text": "Customer data access must follow compliance rules."},
    {"id": 13, "text": "Incident response policy needs escalation contacts."},
    {"id": 14, "text": "Procurement approvals must follow finance limits."},
    {"id": 15, "text": "Email phishing awareness training is overdue."},
    {"id": 16, "text": "API keys must not be stored in source code."},
    {"id": 17, "text": "Policy owner must review expired documents."},
    {"id": 18, "text": "Encryption is required for sensitive files."},
    {"id": 19, "text": "Compliance checklist must be updated before audit."},
    {"id": 20, "text": "Employee exit process must revoke system access."},
    {"id": 21, "text": "Cloud storage policy requires access monitoring."},
    {"id": 22, "text": "Data sharing policy requires manager approval."},
    {"id": 23, "text": "Security patching must be completed within 7 days."},
    {"id": 24, "text": "Financial reports require approval before publishing."},
    {"id": 25, "text": "HR leave policy needs annual review."},
    {"id": 26, "text": "System availability policy requires downtime alerts."},
    {"id": 27, "text": "Confidential files must be labelled correctly."},
    {"id": 28, "text": "Risk assessment must be completed for new vendors."},
    {"id": 29, "text": "Policy lifecycle status must be tracked in dashboard."},
    {"id": 30, "text": "Overdue policies should trigger reminder notification."}
]